/**
 *
 * @format
 */

export const actions = {
  SET_HIGH_ACCURACY: 'SET_HIGH_ACCURACY',
  SET_FORCE_LOCATION: 'SET_FORCE_LOCATION',
  SET_LOCATION_DIALOG: 'SET_LOCATION_DIALOG',
  SET_GPS_INTERVAL: 'SET_GPS_INTERVAL',
  SET_MAP_TYPE: 'SET_MAP_TYPE',
  SET_EMITTERS: 'SET_EMITTERS',
  SET_ERROR: 'SET_ERROR',
  SET_HAS_INTERNET: 'SET_HAS_INTERNET',
  SET_SELECTED_EMITTER: 'SET_SELECTED_EMITTER',
  SET_SELECTED_SENSOR_TYPE: 'SET_SELECTED_SENSOR_TYPE',
};
