/**
 *
 * @format
 */

export const actions = {
  SET_HIGH_ACCURACY: 'SET_HIGH_ACCURACY',
  SET_FORCE_LOCATION: 'SET_FORCE_LOCATION',
  SET_LOCATION_DIALOG: 'SET_LOCATION_DIALOG',
  SET_GPS_INTERVAL: 'SET_GPS_INTERVAL',
  SET_MAP_TYPE: 'SET_MAP_TYPE',
};
